version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.11.6-management-alpine
    container_name: 'message-broker'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=Aa123456
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - message_broker_network

networks:
  message_broker_network:
    driver: bridge