version: "3.2"
services:
  mongo:
    image: mongo
    restart: always
    container_name: order_mongo_service
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
  
  mongo-express:
    image: mongo-express
    restart: always
    container_name: order_mongo_service_ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Aa123456
      ME_CONFIG_MONGODB_URL: mongodb://root:Aa123456@mongo:27017/
  
  rabbitmq:
    image: rabbitmq:3.11.6-management-alpine
    container_name: 'message-broker'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=Aa123456
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - message_broker_network

networks:
  message_broker_network:
    driver: bridge